"""add project_name and progress

Revision ID: a1b2c3d4e5f6
Revises: 2c957a9b6777
Create Date: 2026-04-20 12:45:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '2c957a9b6777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###
