"""add rag chat sessions table

Revision ID: d5fbac244773
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 22:03:57.996411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5fbac244773'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chat_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('last_workflow_node', sa.String(length=50), nullable=True),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_index('ix_session_project_id', 'rag_chat_sessions', ['project_id'], unique=False)
    op.create_index('ix_session_user_id', 'rag_chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_user_id', table_name='rag_chat_sessions')
    op.drop_index('ix_session_project_id', table_name='rag_chat_sessions')
    op.drop_table('rag_chat_sessions')
    # ### end Alembic commands ###

